server:
  port: 5004

spring:
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/auth/**
            - Path=/users/**
            - Path=/api/users/**
            - Path=/
        - id: HOSTEL-SERVICE
          uri: ${HOSTEL_SERVICE_URL}
          predicates:
            - Path=/api/hostel/**
            - Path=/api/student/**

      globalcors:  # ✅ Correct position
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://iiitb-hostel.local"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
